name: jsonschema2md

on: 
  push:
    branches: 
      - master

jobs:
  jsonschemadocs:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: jsonschema2md install
      run: |
        npm install -g @adobe/jsonschema2md
        jsonschema2md -d global/ -o docs/global 
        jsonschema2md -d compiler/ -o docs/compiler 
        jsonschema2md -d script/ -o docs/script
        jsonschema2md -d settings/ -o docs/settings
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages # The branch the action should deploy to.
         FOLDER: build # The folder the action should deploy.
  
