name: jsonschema2md

on: [push, pull_request]

jobs:
  jsonschemadocs:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install -g @adobe/jsonschema2md
    - run: pwd    
    - run: jsonschema2md -d global/ -o docs/
  
