name: SchemaTests

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup black linter
        run: conda create --quiet --name schemas black pytest

      - name: Lint python code
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate schemas
          black --check .

      - name: Running Schema Tests
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate schemas
          pip install -r requirements.txt
          pytest -vra tests
